apiVersion: v1
kind: Namespace
metadata:
  name: network
---
apiVersion: organizations.aws.fcp.io/v1alpha1
kind: Account
metadata:
  name: test-network-account
  namespace: network
spec:
  accountName: "FCP Test Account - Network 1"
  email: "9037f117-ac56-4f6b-bbba-42deafe58097@example.com"
  iamUserAccessToBilling: "DENY"
  ackServicesIAMRoles:
    - roleName: "ACK-CrossAccount-Network"
      services:
        - serviceName: ec2
        - serviceName: ram