apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: organizations.aws.fcp.io/v1alpha1
kind: AdoptedAccount
metadata:
  name: adopt-test-account
  namespace: platform
spec:
  aws:
    accountID: "090172996355"
  kubernetes:
    group: organizations.aws.fcp.io
    kind: Account
    metadata:
      name: test-platform-account
      namespace: platform
  initialUsers:
    - username: "readonly-user"
      managedPolicyARNs:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      generateAccessKey: true
      secretName: "platform-readonly-credentials"
    - username: "admin-user"
      managedPolicyARNs:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
        - "arn:aws:iam::aws:policy/IAMFullAccess"
      generateAccessKey: true
      secretName: "platform-admin-credentials"