apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: organizations.aws.fcp.io/v1alpha1
kind: Account
metadata:
  name: test-platform-account
  namespace: platform
spec:
  accountName: "FCP Test Account - Platform 1"
  email: "d5605732-e816-4ee9-ae48-52309a7d4b23@example.com"
  iamUserAccessToBilling: "DENY"
  ackServicesIAMRoles:
    - roleName: "ACK-CrossAccount-Storage"
      services:
        - serviceName: s3
        - serviceName: rds
        - serviceName: dynamodb
    - roleName: "ACK-CrossAccount-Platform"
      services:
        - serviceName: eks
        - serviceName: iam
        - serviceName: ec2
  initialUsers:
    - username: "readonly-user"
      managedPolicyARNs:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      generateAccessKey: true
      secretName: "platform-readonly-credentials"
    - username: "admin-user"
      managedPolicyARNs:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
        - "arn:aws:iam::aws:policy/IAMFullAccess"
      generateAccessKey: true
      secretName: "platform-admin-credentials"
