---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - organizations.aws.fcp.io
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - organizations.aws.fcp.io
  resources:
  - accounts/finalizers
  verbs:
  - update
- apiGroups:
  - organizations.aws.fcp.io
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
