---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - organizations.aws.fcp.io
  resources:
  - accounts
  - adoptedaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - organizations.aws.fcp.io
  resources:
  - accounts/finalizers
  - adoptedaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - organizations.aws.fcp.io
  resources:
  - accounts/status
  - adoptedaccounts/status
  verbs:
  - get
  - patch
  - update
